.TH "C:/Users/elliot/programming/Zombies/main.c" 3 "Fri May 8 2015" "Version 0.001" "Zombies" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/elliot/programming/Zombies/main.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'main\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBINCLUDE_LOCK\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.RI "\fIWhere everything happens\&. \fP"
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define INCLUDE_LOCK"

.PP
Definition at line 2 of file main\&.c\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.PP
Where everything happens\&. 
.PP
Definition at line 8 of file main\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Zombies from the source code\&.
