.TH "C:/Users/elliot/programming/Zombies/main.h" 3 "Fri May 8 2015" "Version 0.001" "Zombies" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/elliot/programming/Zombies/main.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <pdcurses\\curses\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBentity\fP"
.br
.RI "\fIentity: Used to represent a generic character in the game, can be pretty much anything although at the moment only pits, zombies and the player \fP"
.ti -1c
.RI "struct \fBvectorData\fP"
.br
.RI "\fIVectorData: Used for Holding the position vector of an entity, may be used later for other vectors such as velocity\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Zombies from the source code\&.
