.TH "vectorData" 3 "Fri May 8 2015" "Version 0.001" "Zombies" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vectorData \- VectorData: Used for Holding the position vector of an entity, may be used later for other vectors such as velocity\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <main\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned char \fBxPos\fP"
.br
.ti -1c
.RI "unsigned char \fByPos\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
VectorData: Used for Holding the position vector of an entity, may be used later for other vectors such as velocity\&. 


.PP
Definition at line 31 of file main\&.h\&.
.SH "Field Documentation"
.PP 
.SS "unsigned char xPos"
x position of the vector 
.PP
Definition at line 34 of file main\&.h\&.
.SS "unsigned char yPos"
y position of the vector 
.PP
Definition at line 35 of file main\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Zombies from the source code\&.
